In [4]:
!pip install pandas
!pip install python-docx
!pip install openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: python-docx in /usr/local/lib/python3.10/dist-packages (1.1.2)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from python-docx) (4.9.4)
Requirement already satisfied: typing-extensions>=4.9.0 in /usr/local/lib/python3.10/dist-packages (from python-docx) (4.11.0)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)

# Reading data

In [5]:
import pandas as pd
from docx import Document
import pandas as pd
import numpy as npinstall

data_excel = pd.read_csv('titanic.csv')
data_excel.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
data_cols = data_excel.columns.to_list()
data_cols

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [7]:
def add_header(document):
    section = document.sections[0]
    header = section.header

    # Add a paragraph to the header with your desired content
    paragraph = header.paragraphs[0]
    paragraph.text = "Titanic - List of passengers"

def add_footer(document):
    section = document.sections[0]
    footer = section.footer

    # Add a paragraph to the footer with your desired content
    paragraph = footer.paragraphs[0]
    paragraph.text = "Report - Passneger Details"

In [13]:
for index, row in data_excel.head(3).iterrows():
    document = Document()
    add_header(document)
    add_footer(document)
    document.add_heading('Passenger Details', 0)
    p = document.add_paragraph('The details of the passenger are presented below:')

    table = document.add_table(rows=1, cols=2)
    first_row = table.rows[0].cells
    first_row[0].text = 'Field'
    first_row[1].text = 'Value'
    table.style = 'Table Grid'

    for i in range(len(data_cols)):
        row_cells = table.add_row().cells
        row_cells[0].text = str(data_cols[i])
        row_cells[1].text = str(row[data_cols[i]])

    # export document
    output_file = f'passenger_{row["PassengerId"]}.docx'
    document.save(output_file)